### ISSUE TITLE
Doenst install via composer

### ISSUE THREAD

**Issue by ankitsam** [netglue/ZF2-Maintenance-Mode#1]
Doenst install via composer
Gives error:

 [InvalidArgumentException]
 Could not find package netglue/zf2-maintenance-mode at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by gsteel** [comment]
That's because it hasn't been published on packagist yet. The Readme is simply inaccurate - it is a WIP after all ;) You can change your composer.json to include the repo. You may also need to change your minimum stability setting.

``` json
"require": {
    "netglue/zf2-maintenance-mode":"dev-master"
},
"repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:netglue/ZF2-Maintenance-Mode.git"
        }
    ]
}
```

Tests are also incomplete so let me know how you get on.
